edit category, manager and controller
WildCodeSchool/2023-09-PHP-LYON-P2-perle-do pull request #19
Opened 2023-11-09 14:57 UTC by plbonnier

2023-11-09 15:25 UTC, StoicFrenchDev requested changes

2023-11-09 15:25 UTC, StoicFrenchDev commented on src/View/Category/index.html.twig
> +                        </button>
The element button must not appear as a descendant of the a element.

2023-11-09 15:25 UTC, StoicFrenchDev commented on src/View/Category/index.html.twig
> +                <a href="/categories/add">Nouvelle categoie</a>
The element a must not appear as a descendant of the button element.

2023-11-09 20:05 UTC, nickyrasa approved these changes

2023-11-09 21:49 UTC, StoicFrenchDev requested changes

2023-11-09 21:49 UTC, StoicFrenchDev commented on src/View/Category/index.html.twig
> +        <button class="add-button-customer">
Why didn't you fix this button too?

2023-11-10 08:35 UTC, StoicFrenchDev approved these changes

2023-11-10 08:36 UTC, merged