search page html and css
WildCodeSchool/2023-09-PHP-LYON-P2-perle-do pull request #7
Opened 2023-11-04 14:10 UTC by plbonnier

2023-11-04 15:04 UTC, nickyrasa submitted a review, later dismissed

2023-11-04 15:07 UTC, nickyrasa approved these changes

2023-11-04 15:28 UTC, StoicFrenchDev requested changes
Make sure you follow the best practices for naming your html classes. 
exemple: cancelvalid should be cancel-valid

2023-11-04 15:35 UTC, StoicFrenchDev requested changes
The same applies for other class names from this file

2023-11-05 07:21 UTC, StoicFrenchDev approved these changes

2023-11-05 07:21 UTC, merged